language: php

cache:
    directories:
    - $HOME/.composer/cache

branches:
    only:
    - master
    - /^\d+\.\d+$/

matrix:
    fast_finish: true

    include:
    - php: 7.2
      env:
      - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

    - php: '7.2'

    - php: '7.3'

    - php: '7.4'

    - php: '8.0'
      env:
          - PHPSTAN=true

    - php: '8.1'

install:
- composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
- composer validate --strict --no-check-lock
- if [[ "$PHPSTAN" = true ]]; then composer phpstan-all; fi
- composer phpunit
